export const MOVIE_FETCH_REQUEST = 'MOVIE_FETCH_REQUEST';
export const MOVIE_FETCH_REQUEST_SUCCESS = 'MOVIE_FETCH_REQUEST_SUCCESS';
export const MOVIE_FETCH_REQUEST_FAILURE = 'MOVIE_FETCH_REQUEST_FAILURE';

export const MOVIE_CLEAN_REQUEST = 'MOVIE_CLEAN_REQUEST';

export const MOVIE_DETAIL_FETCH_REQUEST = 'MOVIE_DETAIL_FETCH_REQUEST';
export const MOVIE_DETAIL_FETCH_REQUEST_SUCCESS = 'MOVIE_DETAIL_FETCH_REQUEST_SUCCESS';
export const MOVIE_DETAIL_FETCH_REQUEST_FAILURE = 'MOVIE_DETAIL_FETCH_REQUEST_FAILURE';

export const MOVIE_DETAIL_CLEAN_REQUEST = 'MOVIE_DETAIL_CLEAN_REQUEST';
